server:
  port: 8090

logging:
  level:
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    show-sql: true
  security:
    user:
      name: name
      password: passw0rd
